- type: job
  id: Bailiff
  name: job-name-bailiff
  description: job-description-bailiff
  playTimeTracker: JobWarden
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 86400 # 24 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Security
      time: 64800 # 18 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 21600 # 6 hours
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 150 # 200 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Security
      time: 43200 # 12 hours
  startingGear: BailiffGear
  icon: JobIconBailiff
  supervisors: job-supervisors-sheriff
  weight: 150
  displayWeight: 60
  canBeAntag: false
  access:
  - Armory
  - Sergeant
  - Bailiff
  - Medical
  - Chemistry
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: BailiffGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
    pocket2: HoloprojectorNfsd
  storage:
    back:
    - Flash
    - MagazinePistol
    - MagazinePistolRubber
    - BaseSecurityUplinkRadioOfficer
    - ShipVoucherNfsdBailiff
